# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Termtype < Formula
  desc "A simple typing practice application for your terminal."
  homepage "https://github.com/namest504/termtype"
  version "0.1.0-test"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/namest504/termtype/releases/download/v0.1.0-test/termtype_Darwin_x86_64.tar.gz"
      sha256 "REPLACE_WITH_THE_SHA256_OF_THE_TARBALL"

      def install
        bin.install "termtype"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/namest504/termtype/releases/download/v0.1.0-test/termtype_Darwin_arm64.tar.gz"
      sha256 "REPLACE_WITH_THE_SHA256_OF_THE_TARBALL"

      def install
        bin.install "termtype"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/namest504/termtype/releases/download/v0.1.0-test/termtype_Linux_x86_64.tar.gz"
      sha256 "REPLACE_WITH_THE_SHA256_OF_THE_TARBALL"

      def install
        bin.install "termtype"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/namest504/termtype/releases/download/v0.1.0-test/termtype_Linux_arm64.tar.gz"
      sha256 "REPLACE_WITH_THE_SHA256_OF_THE_TARBALL"

      def install
        bin.install "termtype"
      end
    end
  end

  def caveats
    <<~EOS
      To use termtype, run:
        termtype
    EOS
  end

  test do
    system "#{bin}/termtype --help"
  end
end
