# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Termtype < Formula
  desc "A simple typing practice application for your terminal."
  homepage "https://github.com/namest504/termtype"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/namest504/termtype/releases/download/v0.3.0/termtype_darwin_amd64.tar.gz"
      sha256 "96994d2b9fcdc9cb571acfaca5e5f8413ca9f632582954c3bd3229aa6caed0fc"

      define_method(:install) do
        bin.install "termtype"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/namest504/termtype/releases/download/v0.3.0/termtype_darwin_arm64.tar.gz"
      sha256 "30e4648ff0f73750ad0de5cedc3ade72a45dc5d82ccedd118761147e6eb43b0a"

      define_method(:install) do
        bin.install "termtype"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/namest504/termtype/releases/download/v0.3.0/termtype_linux_amd64.tar.gz"
      sha256 "50e66b5671134a4475d43f095832d80fd24b638e43ef086d5c9eefa04cb59dde"
      define_method(:install) do
        bin.install "termtype"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/namest504/termtype/releases/download/v0.3.0/termtype_linux_arm64.tar.gz"
      sha256 "be7e145ef20671acb945083bc1380998ced9b9f3ea532113ade1efdb3fb1381c"
      define_method(:install) do
        bin.install "termtype"
      end
    end
  end

  test do
    system "#{bin}/termtype", "--version"
  end
end
